# Generated by Django 3.2.21 on 2023-09-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_inscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_de_publicacion',
        ),
    ]
