# Generated by Django 3.2.21 on 2023-09-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_remove_cliente_fecha_de_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(default='Disponible', max_length=100),
        ),
    ]
